#
# NOC & WIRED CONFIGURATION
#
mesh_dim_x: 4
mesh_dim_y: 4
buffer_depth: 4
flit_size: 32

# Routing algorithms:
#   XY
#   WEST_FIRST
#   NORTH_LAST
#   NEGATIVE_FIRST
#   ODD_EVEN
#   DYAD
#   FULLY_ADAPTIVE
#   TABLE_BASED
routing_algorithm: "XY"
routing_table_filename: ""

# Routing specific parameters
#   dyad_threshold: double
dyad_threshold: 0.6

# Selection Strategies
#   SEL_RANDOM             0
#   SEL_BUFFER_LEVEL       1
#   SEL_NOP                2
selection_strategy: 0

#
# WIRELESS CONFIGURATION
#
Hubs:
    defaults:
        rxChannels: [0]
        txChannels:
            0:
                max_hold_cycles: 8
        attachedNodes: []
        toTileBufferSize: 4
        fromTileBufferSize: 4
        rxBufferSize: 4
        txBufferSize: 4

    0:
        attachedNodes: [0,1,4,5]

    1:
        attachedNodes: [2,3,6,7]

    2:
        attachedNodes: [8,9,12,13]

    3:
        attachedNodes: [10,11,14,15]

Channels:
    defaults:
        dataRate: 16
        ber: [0, 0]

    0:
        ber: [0, 0]

#
# SIMULATION PARAMETERS
#
reset_time: 1000
simulation_time: 10000
stats_warm_up_time: 1000
detailed: false
max_volume_to_be_drained: 0
show_buffer_stats: false

# Winoc
use_winoc: false

# Verbosity level:
#   VERBOSE_OFF    0
#   VERBOSE_LOW    1
#   VERBOSE_MEDIUM 2
#   VERBOSE_HIGH   3
verbose_mode: 0

# Trace
trace_mode: false
trace_filename: ""

min_packet_size: 2
max_packet_size: 10
packet_injection_rate: 0.01
probability_of_retransmission: 0.01

# Traffic distribution
#   TRAFFIC_RANDOM         0
#   TRAFFIC_TRANSPOSE1     1
#   TRAFFIC_TRANSPOSE2     2
#   TRAFFIC_HOTSPOT        3
#   TRAFFIC_TABLE_BASED    4
#   TRAFFIC_BIT_REVERSAL   5
#   TRAFFIC_SHUFFLE        6
#   TRAFFIC_BUTTERFLY      7
traffic_distribution: 0
traffic_table_filename: "./TESTS/scenario1/traffic_tables/t0.txt"


Energy:
    Buffer:
    # - [Depth ItemSize Leakage Push Front Pop]
    - [2, 16, 1.1,   2.2,  3.3,  4.4]
    - [2, 32, 5.1,   6.2,  7.3,  8.4]
    - [2, 64, 9.1,  10.2, 11.3, 12.4]
    - [4, 16, 13.1, 14.2, 15.3, 16.4]
    - [4, 32, 17.1, 18.2, 19.3, 20.4]
    - [4, 64, 21.1, 22.2, 23.3, 24.4]
    - [8, 16, 25.1, 26.2, 27.3, 28.4]
    - [8, 32, 29.1, 30.2, 31.3, 32.4]
    - [8, 64, 33.1, 34.2, 35.3, 36.4]

    # LinkBitLine energy in the form [ Length Leakage Dynamic ]
    LinkBitLine:
    - [0.5, 1.0, 11.0e-12]
    - [1,   1.0, 12.0e-12]
    - [1.5, 1.0, 13.0e-12]
    - [2,   1.0, 14.0e-12]

    Router:
        # [Static, Dynamic]
        crossbar:
        # - [I/O Port number, FlitSize, Leakage, Dynamic]
        - [5, 16, 1.0, 1.0] 
        - [5, 32, 1.0, 1.0] 
        - [5, 64, 1.0, 1.0] 
 
        # [Static, Dynamic]
        network_interface: [1.0, 1.0]

        routing:
            # [Static, Dynamic]
            default: [0.1, 0.2]
            XY: [1.1, 1.2]
            DYAD: [2.1, 2.2]

        selection:
            # [Static, Dynamic]
            default: [0.1, 0.2]
            XY: [1.1, 1.2]
            DYAD: [2.1, 2.2]

    Hub:
        # [RX, TX] Contribution
        transceiver_leakage: [1.0, 1.0]
        
        # [RX, TX] Contribution
        transceiver_biasing: [1.0, 1.0]

        rx_dynamic: 1.0
        rx_snooping: 1.0

        default_tx_energy: 1.0
        
        tx_attenuation_map:
        # - [Hub ID TX, Hub ID RX, Attenuation]
        - [0, 1, 1.1]
        - [0, 2, 2.2]
        - [0, 3, 3.3]
        - [1, 0, 1.0]
        - [1, 2, 2.2]
        - [1, 3, 3.3]
        - [2, 0, 1.0]
        - [2, 1, 1.1]
        - [2, 3, 3.3]
        - [3, 0, 1.0]
        - [3, 1, 1.1]
        - [3, 2, 2.2]
