#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$ROOT_DIR/bin"
NOXIM_BIN="$BIN_DIR/noxim"
CONFIG_DIR="$ROOT_DIR/other/regression/configs"
CASES_FILE="$ROOT_DIR/other/regression/cases.txt"
EXPECTED_DIR="$ROOT_DIR/other/regression/expected"
GENERATED_DIR="$ROOT_DIR/other/regression/generated"
TABLE_DIR="$GENERATED_DIR/tables"
LOG_DIR="$GENERATED_DIR/logs"
ACTUAL_DIR="$GENERATED_DIR/actual"

UPDATE_BASELINES=0
SKIP_BUILD=0
LIST_ONLY=0
CASE_FILTER=""

usage() {
    cat <<'EOF'
Usage: ./regression.sh [options]

Options:
  --update        Regenerate expected summaries instead of checking them
  --skip-build    Reuse the current bin/noxim without calling ./build.sh
  --list          List the configured regression cases and exit
  --case NAME     Run only cases whose id contains NAME
  --help          Show this help and exit
EOF
}

parse_args() {
    while (($# > 0)); do
        case "$1" in
            --update)
                UPDATE_BASELINES=1
                ;;
            --skip-build)
                SKIP_BUILD=1
                ;;
            --list)
                LIST_ONLY=1
                ;;
            --case)
                shift
                if (($# == 0)); then
                    echo "Missing value for --case" >&2
                    exit 1
                fi
                CASE_FILTER="$1"
                ;;
            --help)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option: $1" >&2
                usage >&2
                exit 1
                ;;
        esac
        shift
    done
}

case_id() {
    local config_name=$1
    local mode=$2
    local routing=$3
    local selection=$4

    printf "%s__%s__%s__%s" "$config_name" "$mode" "$routing" "$selection"
}

normalize_output() {
    local log_file=$1
    sed -n '/Noxim simulation completed\./,$p' "$log_file" | sed 's/[[:space:]]*$//'
}

ensure_xy_routing_table() {
    local dim_x=$1
    local dim_y=$2
    local output_file=$3
    local nodes=$((dim_x * dim_y))
    local node dst x y dst_x dst_y in_dir in_src in_dst out_src out_dst

    mkdir -p "$(dirname "$output_file")"
    : > "$output_file"
    echo "% XY routing table generated by regression.sh" >> "$output_file"
    echo "% Node        In Dest Outs" >> "$output_file"

    for ((node = 0; node < nodes; node++)); do
        x=$((node % dim_x))
        y=$((node / dim_x))

        for in_dir in NORTH EAST SOUTH WEST LOCAL; do
            case "$in_dir" in
                NORTH)
                    if ((y == 0)); then
                        continue
                    fi
                    in_src=$((node - dim_x))
                    in_dst=$node
                    ;;
                EAST)
                    if ((x == dim_x - 1)); then
                        continue
                    fi
                    in_src=$((node + 1))
                    in_dst=$node
                    ;;
                SOUTH)
                    if ((y == dim_y - 1)); then
                        continue
                    fi
                    in_src=$((node + dim_x))
                    in_dst=$node
                    ;;
                WEST)
                    if ((x == 0)); then
                        continue
                    fi
                    in_src=$((node - 1))
                    in_dst=$node
                    ;;
                LOCAL)
                    in_src=$node
                    in_dst=$node
                    ;;
            esac

            for ((dst = 0; dst < nodes; dst++)); do
                dst_x=$((dst % dim_x))
                dst_y=$((dst / dim_x))

                if ((dst_x > x)); then
                    out_src=$node
                    out_dst=$((node + 1))
                elif ((dst_x < x)); then
                    out_src=$node
                    out_dst=$((node - 1))
                elif ((dst_y > y)); then
                    out_src=$node
                    out_dst=$((node + dim_x))
                elif ((dst_y < y)); then
                    out_src=$node
                    out_dst=$((node - dim_x))
                else
                    out_src=$node
                    out_dst=$node
                fi

                printf " %3d %3d->%3d %3d     %d->%d,\n" \
                    "$node" "$in_src" "$in_dst" "$dst" "$out_src" "$out_dst" >> "$output_file"
            done
        done
    done
}

run_case() {
    local config_name=$1
    local mode=$2
    local routing=$3
    local selection=$4
    local config_path="$CONFIG_DIR/$config_name.yaml"
    local id
    local log_file
    local actual_file
    local expected_file
    local dim_x
    local dim_y
    local table_path=""
    local status=0
    local -a cmd=(./noxim -config "$config_path" -sel "$selection")

    id="$(case_id "$config_name" "$mode" "$routing" "$selection")"
    log_file="$LOG_DIR/$id.log"
    actual_file="$ACTUAL_DIR/$id.txt"
    expected_file="$EXPECTED_DIR/$id.txt"

    if [[ "$routing" == "TABLE_BASED" ]]; then
        if [[ "$config_name" =~ mesh_([0-9]+)x([0-9]+)_buf[0-9]+ ]]; then
            dim_x="${BASH_REMATCH[1]}"
            dim_y="${BASH_REMATCH[2]}"
        else
            echo "Cannot infer mesh dimensions for TABLE_BASED case: $config_name" >&2
            exit 1
        fi
        table_path="$TABLE_DIR/xy_${dim_x}x${dim_y}.rt"
        ensure_xy_routing_table "$dim_x" "$dim_y" "$table_path"
        cmd+=(-routing "$routing" "$table_path")
        # The legacy parser clears packet_injection_rate on TABLE_BASED CLI overrides.
        cmd+=(-pir 0.01 poisson)
    elif [[ "$routing" == "DYAD" ]]; then
        cmd+=(-routing "$routing" 0.6)
    else
        cmd+=(-routing "$routing")
    fi

    if [[ "$mode" == "wireless" ]]; then
        cmd+=(-winoc)
    fi

    echo "[regression] $id"
    if ! (cd "$BIN_DIR" && "${cmd[@]}") >"$log_file" 2>&1; then
        echo "  FAIL: simulator exited with an error, see $log_file" >&2
        return 1
    fi

    normalize_output "$log_file" > "$actual_file"

    if ((UPDATE_BASELINES)); then
        cp "$actual_file" "$expected_file"
        echo "  updated baseline"
        return 0
    fi

    if [[ ! -f "$expected_file" ]]; then
        echo "  FAIL: missing baseline $expected_file" >&2
        return 1
    fi

    if diff -u "$expected_file" "$actual_file" > "$ACTUAL_DIR/$id.diff"; then
        rm -f "$ACTUAL_DIR/$id.diff"
        echo "  ok"
        return 0
    fi

    echo "  FAIL: output changed, see $ACTUAL_DIR/$id.diff" >&2
    return 1
}

load_cases() {
    grep -v '^[[:space:]]*#' "$CASES_FILE" | sed '/^[[:space:]]*$/d'
}

main() {
    local cases
    local config_name mode routing selection id
    local total=0
    local failed=0

    parse_args "$@"

    cases="$(load_cases)"

    if ((LIST_ONLY)); then
        while read -r config_name mode routing selection; do
            id="$(case_id "$config_name" "$mode" "$routing" "$selection")"
            if [[ -n "$CASE_FILTER" && "$id" != *"$CASE_FILTER"* ]]; then
                continue
            fi
            echo "$id"
        done <<< "$cases"
        exit 0
    fi

    mkdir -p "$EXPECTED_DIR" "$LOG_DIR" "$ACTUAL_DIR"

    if ((SKIP_BUILD == 0)); then
        "$ROOT_DIR/build.sh"
    fi

    while read -r config_name mode routing selection; do
        id="$(case_id "$config_name" "$mode" "$routing" "$selection")"
        if [[ -n "$CASE_FILTER" && "$id" != *"$CASE_FILTER"* ]]; then
            continue
        fi

        total=$((total + 1))
        if ! run_case "$config_name" "$mode" "$routing" "$selection"; then
            failed=$((failed + 1))
        fi
    done <<< "$cases"

    if ((total == 0)); then
        echo "No regression cases matched the current selection." >&2
        exit 1
    fi

    if ((failed > 0)); then
        echo "[regression] $failed of $total case(s) failed" >&2
        exit 1
    fi

    if ((UPDATE_BASELINES)); then
        echo "[regression] Updated $total baseline(s)"
    else
        echo "[regression] All $total case(s) passed"
    fi
}

main "$@"
